### ISSUE TITLE
Clipboard tool TODO

### ISSUE THREAD

**Issue by Alan-FGR** [raizam/gamedev_libraries#6]
- [ ] format link texts as user/repo not just repo
- [ ] automatically update index on save
- [ ] sanitize spaces and newlines
- [ ] capitalize descriptions
- [ ] allow creation of new categories
- [ ] allow dnd sorting of entries/categories

**Comment by raizam** [comment]
I'm removing your python script, cause github thinks this repo is a python app.
could you please publish that script as a gist?

**Comment by Alan-FGR** [comment]
Are you saying *"f#$k this contribution"*? :trollface:
Yes, go ahead, no problem.

**Comment by raizam** [comment]
that's pretty much it, but in a very polite style :)
cc @bkaradzic

**Comment by bkaradzic** [comment]
Totally non-welcoming README.md repo. :)

**Comment by raizam** [comment]
you mean a nice and organized junkyard is not welcoming? :)

**Comment by raizam** [comment]
adding the header to https://user-images.githubusercontent.com/2153610/45614134-c805f980-ba68-11e8-95ab-caba774feb54.jpg
![header](https://user-images.githubusercontent.com/2153610/45614134-c805f980-ba68-11e8-95ab-caba774feb54.jpg)
